/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Ficha;
import Modelo.Juego;
import Modelo.Jugador;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JOptionPane;



/**
 *
 * @author LENOVO
 */
public class PantallaTablero extends javax.swing.JFrame {
 
    private Juego juego;
    private Ficha fichaJugador1;
    private Ficha fichaJugador2;

    private int[][] posicionesCasillas = {
        {290, 470}, {310, 470}, {330, 470}, {350, 470}, {370, 470}, {390, 470},
        {410, 470}, {430, 470}
    };
    public PantallaTablero() {
        initComponents();
        inicializarJuego();
          
    }
    
    public JButton getBtnTirarDado() {
        return btnTirarDado;  
    }

    private void inicializarJuego() {
       fichaJugador1 = new Ficha("Rojo");
       fichaJugador2 = new Ficha("Azul");

       Jugador jugador1 = new Jugador("Jugador 1", "Rojo", Arrays.asList(fichaJugador1));
       Jugador jugador2 = new Jugador("Jugador 2", "Azul", Arrays.asList(fichaJugador2));

       juego = new Juego();
       juego.agregarJugador(jugador1);
       juego.agregarJugador(jugador2);
       juego.iniciarJuego();

       lblTurno.setText("Turno: " + juego.getJugadorActual().getNombre());
    }

    public void moverFicha(Ficha ficha, int nuevaPos) {
        // Si la ficha aún no tiene posición, empieza en 0
        if (nuevaPos < 0) {
            nuevaPos = 0;
        }

        // Limita a los bordes del tablero
        if (nuevaPos >= posicionesCasillas.length) {
            nuevaPos = posicionesCasillas.length - 1;
        }

        lblFicha.setBounds(
            posicionesCasillas[nuevaPos][0],
            posicionesCasillas[nuevaPos][1],
            20, 25
        );
    }

    public void actualizarDado(int valor) {
        lblResultado1.setText("Resultado: " + valor); 
    }

//    public void setTurno(String texto) {
//        lblTurno.setText(texto);
//    }
    
    public void setTurnoJugador(String nombreJugador) {
        if (nombreJugador.equals("Jugador 1")) {
            lblTurno.setText("Turno: Jugador 1");
            lblTurno2.setText("");
        } else {
            lblTurno2.setText("Turno: Jugador 2");
            lblTurno.setText("");
        }
    }

    public void actualizarTurnoYResultado(String nombreJugador, int resultado) {
        if (nombreJugador.equals("Jugador 1")) {
            lblTurno.setText("Turno: Jugador 1");
            lblResultado1.setText("Resultado: " + resultado);
            lblTurno2.setText(""); // limpia el otro
        } else {
            lblTurno2.setText("Turno: Jugador 2");
            lblResultado2.setText("Resultado: " + resultado);
            lblTurno.setText("");
        }
    }



    public void mostrarMensaje(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg);
    }


  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTurno1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblFicha = new javax.swing.JLabel();
        lblConfiguracion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTirarDado = new javax.swing.JButton();
        lblTurno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblResultado1 = new javax.swing.JLabel();
        lblResultado2 = new javax.swing.JLabel();
        lblTurno2 = new javax.swing.JLabel();

        lblTurno1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTurno1.setForeground(new java.awt.Color(255, 255, 255));
        lblTurno1.setText("Turno:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pawn.png"))); // NOI18N
        jPanel1.add(lblFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 20, 25));

        lblConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/menu.png"))); // NOI18N
        jPanel1.add(lblConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, 43, 41));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Parchis555 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 207, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Jugardor2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 55, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Avatarr.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 55, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Avatarr.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 55, 60));

        btnTirarDado.setBackground(new java.awt.Color(102, 0, 102));
        btnTirarDado.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        btnTirarDado.setForeground(new java.awt.Color(204, 204, 255));
        btnTirarDado.setText("Tirar Dado");
        btnTirarDado.setBorder(null);
        btnTirarDado.setBorderPainted(false);
        btnTirarDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTirarDadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnTirarDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 95, 33));

        lblTurno.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTurno.setForeground(new java.awt.Color(255, 255, 255));
        lblTurno.setText("Turno:");
        jPanel1.add(lblTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 180, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Jugardor2.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 55, 60));

        lblResultado1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblResultado1.setForeground(new java.awt.Color(255, 255, 255));
        lblResultado1.setText("Resultado:");
        jPanel1.add(lblResultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 100, 30));

        lblResultado2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblResultado2.setForeground(new java.awt.Color(255, 255, 255));
        lblResultado2.setText("Resultado:");
        jPanel1.add(lblResultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 660, 130, 30));

        lblTurno2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTurno2.setForeground(new java.awt.Color(255, 255, 255));
        lblTurno2.setText("Turno:");
        jPanel1.add(lblTurno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 690, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 430, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTirarDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTirarDadoActionPerformed
        Jugador jugador = juego.getJugadorActual();

        int resultado = juego.lanzarDado();
        actualizarDado(resultado);

        Ficha ficha = jugador.getFichas().get(0); // mover la primera ficha por simplicidad
        moverFicha(ficha, resultado - 1);

        // Verificar si llega a meta
        if (ficha.isEnMeta()) {
            mostrarMensaje("🎉 " + jugador.getNombre() + " ha llegado a la meta!");
            btnTirarDado.setEnabled(false);
            return;
        }

        // Cambiar turno
        if (resultado != 6) {
            juego.siguienteTurno();
        }

        String siguiente = juego.getJugadorActual().getNombre();
        setTurnoJugador(siguiente);
    }//GEN-LAST:event_btnTirarDadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTirarDado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfiguracion;
    private javax.swing.JLabel lblFicha;
    private javax.swing.JLabel lblResultado1;
    private javax.swing.JLabel lblResultado2;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JLabel lblTurno1;
    private javax.swing.JLabel lblTurno2;
    // End of variables declaration//GEN-END:variables
}
